services:

  identifier:
    ports:
      - "80:80"

  triplestore:
    ports:
      - "8890:8890"

  project-scripts:
    image: semtech/mu-scripts:1.0.0
    volumes:
      - ./scripts/project:/app/scripts/

