services:

  frontend:
    image: lblod/app-erfgoed-lblod-groep6:1.0.0
    links:
      - identifier:backend
    labels:
      - "logging=true"
    restart: always

  identifier:
    image: semtech/mu-identifier:1.10.3
    environment:
      SESSION_COOKIE_SECURE: "on"
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"}]"
    links:
      - dispatcher:dispatcher
    restart: always

  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
    restart: always

  triplestore:
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    restart: always

  database:
    image: semtech/mu-authorization:0.6.0-beta.8
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
      DATABASE_OVERLOAD_RECOVERY: "true"
      DATABASE_COMPATIBILITY: "Virtuoso"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: always

  resource:
    image: semtech/mu-cl-resources:1.23.0
    links:
      - database:database
    volumes:
      - ./config/resources:/config
    restart: always

