PREFIX persons: <http://data.lblod.info/id/persons/>
PREFIX identifiers: <http://data.lblod.info/id/identifiers/>
PREFIX adresses: <http://data.lblod.info/id/addresses/>
PREFIX addressRepresentations: <http://data.lblod.info/id/address-representations/>
PREFIX contactPoints: <http://data.lblod.info/id/contact-points/>
PREFIX locationParcels: <http://data.lblod.info/id/location-parcels/>
PREFIX objecten: <https://inventaris.onroerenderfgoed.be/aanduidingsobjecten/>
PREFIX postalItems: <http://data.lblod.info/id/postal-items/>
PREFIX cases: <http://data.lblod.info/id/cases/>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
}
INSERT {
  GRAPH <http://data.lblod/graphs/admin/353234a365664e581db5c2f7cc07add2534b47b8e1ab87c821fc6e6365e6bef5> {
    ?s ?p ?o .
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    VALUES ?s {
      persons:34e587ee-d54c-477e-8e5f-f84250f84946
      identifiers:f8dec766-9d8f-4559-b1cb-567be7bc6501
      adresses:5539f031-e4c1-4fbb-8c3b-01dbe277031a
      addressRepresentations:31e35f19-7727-4142-8c43-0f084d62d122
      contactPoints:827ec53f-7b66-40ad-8a87-59a3e4d015c3
      persons:255bafb7-0b26-462f-a013-35b2618efc85 
      identifiers:909be2c5-e778-466f-91ec-4043bce0312e 
      adresses:6d7752a3-1e0e-48cb-87b2-3ca4dadcdc5b
      addressRepresentations:6ced0ead-cc12-4472-8d2d-3036051c4021
      contactPoints:aa68612f-2778-4523-a3a9-deec774d9ea9 
    }
    ?s ?p ?o .
  }
}
